# Phase 11 - Days 197-212 : Unsupervised ML + Time Series
DAYS = [
    (197, "Unsupervised Learning Landscape and Distance Metrics", "Supervised vs unsupervised objectives|Similarity and distance families|Euclidean, manhattan, cosine, jaccard|Scaling before distance|Evaluating without labels",
     "109,110", "07_machine_learning/unsupervised_machine_learning/15_k_means_all.ipynb", 3, "src"),
    (198, "K-Means Clustering: Theory and Mathematics", "Objective: within-cluster sum of squares|Lloyd's algorithm steps|Convergence and local minima|K-means++ initialisation|Assumptions: spherical, similar size",
     "110,111", "07_machine_learning/unsupervised_machine_learning/15_k_means_all.ipynb", 3, "src"),
    (199, "K-Means in Practice: Choosing K", "Elbow method and its weaknesses|Silhouette, Calinski-Harabasz, Davies-Bouldin|Inertia curve interpretation|Mini-batch k-means for large data|Full sklearn workflow and visualisation",
     "111,112", "07_machine_learning/unsupervised_machine_learning/15_k_means_all.ipynb", 3, "src"),
    (200, "Hierarchical Clustering", "Agglomerative vs divisive|Linkage criteria: single, complete, average, ward|Dendrograms and cutting height|Distance matrix cost|Comparing with k-means on the same data",
     "113,114", "07_machine_learning/unsupervised_machine_learning/16-heirarchical-clustering.ipynb", 3, "src"),
    (201, "DBSCAN and OPTICS", "Density-based clustering idea|Core, border and noise points|eps and min_samples selection|Advantages on arbitrary shapes|OPTICS and reachability plots",
     "115,116", "07_machine_learning/unsupervised_machine_learning/17_dbscan_and_optics_clustering.ipynb", 3, "src"),
    (202, "Gaussian Mixture Models, EM and Cluster Evaluation", "Mixture of Gaussians model|Expectation-Maximisation walkthrough|Covariance types and model selection with BIC/AIC|Soft assignments and probabilities|Evaluating clusters without labels",
     "117,118", "07_machine_learning/unsupervised_machine_learning/18_gmms.ipynb", 3, "src"),
    (203, "Dimensionality Reduction and PCA Theory", "Why reduce dimensions|Curse of dimensionality|Variance maximisation derivation|Eigen-decomposition of the covariance matrix|Loadings, scores and reconstruction",
     "121,203", "07_machine_learning/unsupervised_machine_learning/20_PCA.ipynb", 3, "src"),
    (204, "PCA in Practice", "Scaling before PCA|Choosing components: scree plot and explained variance|Biplots and loadings interpretation|PCA for visualisation vs for modelling|Reconstruction error and denoising",
     "122,204", "07_machine_learning/unsupervised_machine_learning/20_PCA.ipynb", 3, "src"),
    (205, "Singular Value Decomposition and Matrix Factorisation", "A = U S V^T interpretation|Relationship between SVD and PCA|Low-rank approximation and Eckart-Young|Truncated SVD for sparse text data|Collaborative filtering intuition",
     "123,205", "07_machine_learning/unsupervised_machine_learning/22_SVD.ipynb", 3, "src"),
    (206, "t-SNE and UMAP", "Manifold learning motivation|t-SNE perplexity and neighbourhood preservation|Why t-SNE distances are not global|UMAP parameters and speed|Comparing embeddings visually, honestly",
     "124,206", "07_machine_learning/unsupervised_machine_learning/21_t_SNE.ipynb", 3, "src"),
    (207, "Anomaly Detection", "Supervised vs unsupervised anomaly detection|Z-score and IQR baselines|Isolation Forest mechanics|Local Outlier Factor and One-Class SVM|Evaluating anomaly models and alerting thresholds",
     "27,207", "07_machine_learning/04_outliers.ipynb", 3, "mix"),
    (208, "Cluster Interpretation and Unsupervised Project", "Naming and profiling clusters|Cluster-level statistics and personas|Business storytelling with clusters|Project: customer segmentation end to end|Deliverable and evaluation rubric",
     "112,118,208", "07_machine_learning/unsupervised_machine_learning", 3, "src"),
    (209, "Time Series Fundamentals and Components", "Time series vs cross-sectional data|Trend, seasonality, cycle, irregular|Additive vs multiplicative decomposition|Types of time series data|Business time series examples",
     "158,159,160", "08_deep_learning_with_tensorflow/10_time_series.ipynb", 3, "src"),
    (210, "Time Series EDA, Stationarity and Autocorrelation", "Datetime index and resampling|Rolling statistics and decomposition|Stationarity definition and tests (ADF, KPSS)|ACF and PACF reading|Differencing and transformations",
     "160,161,210", "08_deep_learning_with_tensorflow/10_time_series.ipynb", 3, "src"),
    (211, "ARIMA and SARIMA", "AR, MA, ARMA model intuition|ARIMA(p,d,q) parameters|Seasonal orders (P,D,Q,m)|Model selection with AIC and residual checks|Coding ARIMA and SARIMA in statsmodels",
     "171,172,173,211", "08_deep_learning_with_tensorflow/18_arima.ipynb;08_deep_learning_with_tensorflow/19_SARIMA.ipynb", 3, "src"),
    (212, "SARIMAX, Prophet, Forecast Evaluation and Project", "Exogenous variables in SARIMAX|Prophet components: trend, seasonality, holidays|Backtesting and rolling-origin evaluation|MAE, RMSE, MAPE and MASE for forecasts|Project: weather/holiday forecasting end to end",
     "174,166,167,212", "08_deep_learning_with_tensorflow/13_time_searies_prophet.ipynb;08_deep_learning_with_tensorflow/14_jena_prophet_model.ipynb", 3, "src"),
]
