# Phase 10 - Days 165-196 : Machine Learning
DAYS = [
    (165, "What Machine Learning Actually Is", "Programs that learn from data|Supervised, unsupervised, self-supervised, reinforcement|Parametric vs non-parametric|Bias-variance vocabulary|When NOT to use ML",
     "73,74", "07_machine_learning/09_basic_model_coding.ipynb", 2, "src"),
    (166, "The Supervised Learning Workflow and Data Leakage", "Framing: X and y|Train, validation, test splits|Cross-validation preview|Data leakage: target, temporal, preprocessing|Baseline-first modelling discipline",
     "74,75,76", "07_machine_learning/09_basic_model_coding.ipynb", 3, "src"),
    (167, "Preprocessing: Scaling and Encoding", "Standardisation vs normalisation vs robust scaling|When distance-based models need scaling|One-hot, ordinal, target and binary encoding|High-cardinality strategies|Fit on train, transform on test",
     "36,167", "03_Feature_scaling_and_encoding/01_feature_scaling.ipynb;03_Feature_scaling_and_encoding/02_feature_encoding.ipynb", 3, "src"),
    (168, "Feature Engineering and Feature Selection", "Feature creation from domain knowledge|Interaction and polynomial features|Binning and discretisation|Filter, wrapper, embedded selection|Variance threshold and mutual information",
     "119,120", "07_machine_learning/unsupervised_machine_learning/19_feature_engineering.ipynb;07_machine_learning/unsupervised_machine_learning/20_feature_selection.ipynb", 3, "src"),
    (169, "Pipelines and ColumnTransformer", "Why pipelines prevent leakage|Pipeline steps and naming|ColumnTransformer for mixed dtypes|Nested pipelines and feature unions|Saving pipelines with joblib",
     "97,98,169", "07_machine_learning/20_pipeline.ipynb", 3, "src"),
    (170, "Linear Regression I: Model and Mathematics", "The line equation for many features|Ordinary least squares objective|Normal equation vs gradient descent|Interpreting coefficients and units|Implementing from NumPy to sklearn",
     "76,106", "07_machine_learning/10_linear_regression.ipynb", 3, "src"),
    (171, "Linear Regression II: Assumptions and Diagnostics", "Linearity, independence, homoscedasticity|Normality of residuals|Multicollinearity and VIF|Residual plots and QQ plots|Influence, leverage and Cook's distance",
     "76,171", "07_machine_learning/10_linear_regression.ipynb", 3, "ext"),
    (172, "Gradient Descent in Machine Learning", "Batch, stochastic, mini-batch|Learning rate schedules|Convergence diagnostics|Feature scaling's role in convergence|Implementing GD for linear regression",
     "106,172", "07_machine_learning/10_linear_regression.ipynb", 3, "src"),
    (173, "Polynomial Regression", "Capturing non-linearity by basis expansion|Degree selection and overfitting|Interaction terms|Comparing with splines preview|Practice on curved data",
     "76,173", "07_machine_learning/10a_polynomial_regression.ipynb", 3, "src"),
    (174, "Regularisation: Ridge, Lasso and Elastic Net", "Why regularisation works (bias-variance)|L2 penalty and coefficient shrinkage|L1 penalty and sparsity|Elastic Net mixing parameter|Tuning alpha with cross-validation",
     "76,174", "07_machine_learning/10b_ridge_regression.ipynb;07_machine_learning/10c_lasso_regression.ipynb", 3, "src"),
    (175, "Beyond Least Squares: Robust, Bayesian, Quantile and Poisson Regression", "Huber and RANSAC for outliers|Bayesian linear regression and posterior coefficients|Quantile regression for prediction intervals|Poisson regression for counts (GLM)|Choosing the right regression family",
     "175", "07_machine_learning/27_all_models.ipynb", 3, "ext"),
    (176, "KNN Regression and Support Vector Regression", "KNN: distance-based prediction|Choosing k and distance metric|Curse of dimensionality|SVR with epsilon tube and kernels|Kernel trick intuition",
     "77,78", "07_machine_learning/13_knn.ipynb;07_machine_learning/12_support_vector_machines.ipynb", 3, "src"),
    (177, "Decision Tree Regression", "Recursive binary splitting|Variance reduction criterion|Depth, min_samples and pruning|Tree visualisation and interpretation|Instability of single trees",
     "86,177", "07_machine_learning/14_decision_tree.ipynb", 3, "src"),
    (178, "Random Forest Regression", "Bagging and random feature subsets|Why averaging reduces variance|OOB score and feature importance|Tuning n_estimators, max_features, depth|Coding a full random forest pipeline",
     "87,178", "07_machine_learning/15_random_forest.ipynb", 3, "src"),
    (179, "Bagging, Extra Trees and AdaBoost Regression", "Bootstrap aggregation recap|Extra Trees randomness|Adaptive boosting: reweighting errors|Learning rate and weak learners|Comparing ensembles empirically",
     "87,91", "07_machine_learning/16_boosting.ipynb", 3, "src"),
    (180, "Gradient Boosting Regression", "Boosting as functional gradient descent|Residual fitting intuition|Shrinkage, subsample and depth|Early stopping with validation|sklearn GradientBoostingRegressor in practice",
     "91,180", "07_machine_learning/16_boosting.ipynb", 3, "src"),
    (181, "XGBoost Regression", "Regularised objective and second-order approximation|Handling missing values natively|Key parameters: eta, gamma, lambda, alpha|Early stopping and best iteration|Full modelling walkthrough",
     "181", "00_projects/best_model_selection/usman_tariq_models_comparisons.ipynb", 3, "src"),
    (182, "LightGBM Regression", "Histogram-based splitting|Leaf-wise growth vs level-wise|Leaf count and min_child_samples|Categorical feature support|Speed comparison on large data",
     "182", "00_projects/best_model_selection/bilal_diamond_model_comparison.ipynb", 3, "src"),
    (183, "CatBoost Regression", "Ordered boosting and target leakage in categoricals|Oblivious trees|Native categorical handling|Training logs and GPU options|Practical parameter tuning",
     "92,183", "07_machine_learning/17_catboost.ipynb", 3, "src"),
    (184, "Regression Capstone: The Complete Model Bake-Off", "Same data, ranking 16+ regression models|Leak-free preprocessing pipeline|Cross-validated comparison table|Error analysis on the winner|When a simpler model wins",
     "101,102,184", "07_machine_learning/27_all_models.ipynb;00_projects/best_model_selection", 3, "src"),
    (185, "Classification: Logistic Regression", "Why linear regression fails for classes|Sigmoid and log-odds|Maximum likelihood and log loss|Decision threshold and probability calibration|Regularisation and multiclass (softmax)",
     "79,104,185", "07_machine_learning/11_logistic_regression.ipynb", 3, "src"),
    (186, "KNN and Naive Bayes Classifiers", "KNN classification and decision boundaries|Curse of dimensionality and scaling|Naive Bayes assumption and why it works|Gaussian, Multinomial and Bernoulli variants|Text classification with Naive Bayes",
     "77,99", "07_machine_learning/13_knn.ipynb;07_machine_learning/22_naive_bayes.ipynb", 3, "src"),
    (187, "Decision Tree Classification and Interpretation", "Gini and entropy criteria|Information gain computation|Tree depth and pruning strategies|Reading and explaining a tree|Rule extraction for stakeholders",
     "86,187", "07_machine_learning/14_decision_tree.ipynb;07_machine_learning/saved_models/Decision_tree_01.dot", 3, "src"),
    (188, "Random Forest Classification and Feature Importance", "Ensemble of trees for classification|Voting and probability averaging|Impurity vs permutation importance|Bias in impurity importance|Building and interpreting the forest",
     "87,188", "07_machine_learning/15_random_forest.ipynb", 3, "src"),
    (189, "Support Vector Machines", "Maximum margin classifier|Support vectors and slack variables|C parameter and the margin trade-off|Linear, polynomial and RBF kernels|Kernel trick and gamma",
     "78,189", "07_machine_learning/12_support_vector_machines.ipynb", 3, "src"),
    (190, "Gradient Boosting Classification", "Log loss optimisation with trees|Binary and multiclass strategies|Early stopping and shrinkage|Comparing with random forest|Practical modelling recipe",
     "91,190", "07_machine_learning/16_boosting.ipynb", 3, "src"),
    (191, "AdaBoost and XGBoost Classification", "Adaptive reweighting for classifiers|SAMME algorithm intuition|XGBoost classifier specifics: scale_pos_weight|Early stopping and evaluation metrics|Hands-on comparison",
     "91,191", "07_machine_learning/16_boosting.ipynb", 3, "src"),
    (192, "LightGBM and CatBoost Classification", "LightGBM for imbalanced classification|CatBoost ordered boosting for categoricals|GPU training and prediction|Comparing speed and accuracy|Which booster to choose when",
     "92,192", "07_machine_learning/17_catboost.ipynb;00_projects/03_bank_churn_kaggle_competition/catboost_info", 3, "src"),
    (193, "Regression Metrics: MAE, MSE, RMSE and R2", "Absolute vs squared error trade-offs|RMSE units and interpretability|R2 definition and pitfalls|Adjusted R2 and MAPE, SMAPE|Choosing metrics by business cost",
     "89,193", "07_machine_learning/19_cross_validation.ipynb", 3, "src"),
    (194, "Classification Metrics and the Confusion Matrix", "Confusion matrix layout and derived metrics|Accuracy paradox with imbalance|Precision, recall, F1 and F-beta|ROC-AUC vs PR-AUC|Threshold selection with business costs",
     "90,194", "00_projects/03_bank_churn_kaggle_competition/figures/model_evaluation_metrics.png", 3, "src"),
    (195, "Cross-Validation, Tuning and Imbalanced Data", "K-fold, stratified, grouped and time-series CV|GridSearchCV and RandomizedSearchCV|Halving search and nested CV|Resampling: SMOTE, class weights, threshold moving|Leakage-safe tuning with pipelines",
     "93,94,95,96,195", "07_machine_learning/18_hyperparameter_tuning.ipynb;07_machine_learning/19_cross_validation.ipynb;07_machine_learning/23_hyperparamterr_tunning_and_best_model_selection.ipynb", 3, "src"),
    (196, "Explainability, Error Analysis and Model Comparison", "Global vs local explanation|Permutation importance and partial dependence|SHAP values intuition and plots|Slice-based error analysis|Model comparison report and production checklist",
     "98,196", "07_machine_learning/21_best_model_selection.ipynb;00_projects/best_model_selection", 3, "mix"),
]
