# Phase 7 - Days 113-134 : Statistics
DAYS = [
    (113, "What Statistics Is and Types of Data", "Descriptive vs inferential statistics|Population vs sample|Nominal, ordinal, interval, ratio scales|Discrete vs continuous data|Choosing the right summary",
     "59,60", "06_statistics/01_central Tendency.ipynb", 1, "src"),
    (114, "Descriptive Statistics: Central Tendency", "Mean and its sensitivity to outliers|Median and robust centre|Mode for categorical data|Weighted mean and trimmed mean|Which centre to report and why",
     "59,60,64", "06_statistics/01_central Tendency.ipynb", 2, "src"),
    (115, "Spread: Range, Variance and Standard Deviation", "Range and IQR|Variance formula and degrees of freedom|Population vs sample SD|Coefficient of variation|Standardising with z-scores",
     "61,62,64", "06_statistics/01_central Tendency.ipynb", 2, "src"),
    (116, "Percentiles, Quartiles and the IQR", "Percentile definition and interpolation|Quartiles and five-number summary|IQR outlier rule|Cutting continuous variables into bins|Boxplot statistics in pandas",
     "62,75", "06_statistics/01_central Tendency.ipynb;07_machine_learning/04_outliers.ipynb", 2, "src"),
    (117, "Skewness and Kurtosis", "Symmetry detection|Positive and negative skew|Kurtosis and tail heaviness|Impact on mean-based methods|Transformations: log, sqrt, Box-Cox",
     "63,74", "06_statistics/02_distribution.ipynb", 3, "src"),
    (118, "Probability Distributions Overview", "Discrete vs continuous distributions|PMF, PDF and CDF reading|Uniform, Bernoulli, binomial, Poisson, normal, exponential|Parameters, mean and variance of each|Sampling from distributions in NumPy",
     "60,63,66", "06_statistics/02_distribution.ipynb", 3, "src"),
    (119, "The Normal Distribution and z-scores", "Bell curve parameters mu and sigma|Empirical 68-95-99.7 rule|z-scores and standard normal table|Standardisation vs normalisation|Why normality is often assumed",
     "63,64,119", "06_statistics/02_distribution.ipynb", 3, "src"),
    (120, "Binomial and Bernoulli Distributions", "Bernoulli trial|Binomial PMF and parameters|Mean and variance formulas|Applications: conversion, defect rate, clicks|Binomial approximation to proportion testing",
     "66,67", "06_statistics/02_distribution.ipynb", 3, "src"),
    (121, "Poisson and Other Discrete Distributions", "Poisson process assumptions|PMF and rate parameter lambda|Mean equals variance property|Geometric and negative binomial|Applications: arrivals, counts, incidents",
     "67,68", "06_statistics/02_distribution.ipynb", 3, "src"),
    (122, "Sampling Methods and Bias", "Why we sample|Simple random, systematic, stratified, cluster|Convenience and survivorship bias|Sampling frame problems|Sample size intuition and back-of-envelope n",
     "68,69,122", "06_statistics/07_case_study.ipynb", 3, "src"),
    (123, "Sampling Distributions", "Statistic as a random variable|Distribution of the sample mean|Standard error and the sqrt(n) law|Simulating sampling distributions|Why this underpins all inference",
     "69,70", "06_statistics/03_statistical_tests.ipynb", 3, "src"),
    (124, "The Central Limit Theorem", "Statement and conditions|CLT for means, proportions and sums|Simulation experiments with skew and small n|When CLT fails|Practical consequences for A/B testing",
     "70,71", "06_statistics/03_statistical_tests.ipynb", 3, "src"),
    (125, "Standard Error and Confidence Intervals", "Point estimate vs interval|SE formula for mean and proportion|95 percent CI construction and interpretation|Common misinterpretations|Bootstrap confidence intervals",
     "71,72", "06_statistics/03_statistical_tests.ipynb", 3, "src"),
    (126, "Hypothesis Testing Logic", "Null and alternative hypotheses|One-tailed vs two-tailed|Test statistic and decision rule|Significance level alpha|Stating conclusions honestly",
     "72,73", "06_statistics/03_statistical_tests.ipynb", 3, "src"),
    (127, "p-values: What They Are and Are Not", "Definition: probability of data given H0|Simulation-built intuition|p > 0.05 is not proof of no effect|p-hacking and multiple comparisons|Reporting p-values well",
     "73,127", "06_statistics/03_statistical_tests.ipynb", 3, "src"),
    (128, "Type I and Type II Errors, Power and Effect Size", "Error table|alpha, beta and power|Effect size: Cohen's d, eta squared|Power analysis and sample size planning|Practical vs statistical significance",
     "73,74", "06_statistics/03_statistical_tests.ipynb", 3, "ext"),
    (129, "z-tests and t-tests", "When to use z vs t|One-sample t-test|Independent two-sample t-test (Welch)|Assumption checks|Implementing with scipy.stats",
     "73,74,129", "06_statistics/03_statistical_tests.ipynb", 3, "src"),
    (130, "Paired Tests and Analysis of Variance (ANOVA)", "Paired t-test and repeated measures|One-way ANOVA logic|F-statistic and between/within variance|Post-hoc tests: Tukey HSD|Two-way ANOVA preview",
     "74,130", "06_statistics/04_anova.ipynb", 3, "src"),
    (131, "Chi-Square Tests and MANOVA", "Chi-square goodness of fit|Test of independence and contingency tables|Expected vs observed counts|Cramer's V effect size|MANOVA with multiple dependent variables",
     "74,131", "06_statistics/05_manova.ipynb", 3, "src"),
    (132, "Covariance and Correlation Deep Dive", "Covariance and its units problem|Pearson r and its assumptions|Spearman and Kendall for ranks|Correlation matrix and multicollinearity|Spurious correlation and confounders",
     "78,132", "06_statistics/06_correlation.ipynb", 3, "src"),
    (133, "A/B Testing in Practice", "Experiment design: hypothesis, metric, MDE|Randomisation and assignment|Sample size and duration calculation|Sequential testing and peeking problems|Analysis, segment checks and decision memos",
     "70,71,133", "00_projects/02_titanic_kaggle_competition/titanic_kaggle.ipynb", 3, "ext"),
    (134, "Statistics Case Study and Assessment", "Full case study on real data|Choosing tests defensibly|Reporting statistical findings|Common statistical mistakes in industry|Assessment: 40 questions + analysis notebook",
     "72,134", "06_statistics/07_case_study.ipynb", 3, "src"),
]
