# Phase 4 - Days 49-70 : Pandas + Data Cleaning + EDA
DAYS = [
    (49, "Series: The One-Dimensional Workhorse", "Series anatomy: values + index|Creating Series from lists and dicts|Alignment on index|Vectorised operations on Series|Series vs NumPy array + named index",
     "17,18", "01_pandas_tips_tricks/01_pandas.ipynb", 2, "src"),
    (50, "DataFrame Anatomy", "Rows, columns and index|Building DataFrames from dicts and arrays|dtypes per column|Index vs column confusion|Copy vs view in pandas",
     "17,18,19", "01_pandas_tips_tricks/01_pandas.ipynb", 2, "src"),
    (51, "Reading Data: CSV, Excel, JSON and SQL", "read_csv arguments you actually need|read_excel and sheet selection|read_json and normalisation|read_sql with SQLAlchemy|Encoding, delimiters and dirty files",
     "17,18,19,20", "01_pandas_tips_tricks/01_pandas.ipynb;01_pandas_tips_tricks/data/googleplaystore.csv;resources/datasets_for_practice/Sample_Superstore.xlsx", 2, "src"),
    (52, "First Look: Profiling a Dataset", "head, tail, sample|info and describe|shape, columns, dtypes, memory_usage|Value counts and uniqueness|ydata-profiling report",
     "17,19,20", "01_pandas_tips_tricks/03_ydata_profiling.ipynb", 2, "src"),
    (53, "Selection: loc, iloc, at, iat", "Label vs position based indexing|loc with slices and conditions|iloc with integers only|Setting values safely|The SettingWithCopyWarning explained",
     "18,19,20", "01_pandas_tips_tricks/02_pandas_on_pak_pop.ipynb", 2, "src"),
    (54, "Filtering, Query and Sorting", "Boolean masks and & | ~|isin, between, str.contains|query() for readable filters|Sorting by one and many columns|nlargest and nsmallest",
     "18,19,26", "01_pandas_tips_tricks/04a_EDA_google_playstore_data.ipynb", 2, "src"),
    (55, "Sorting, Ranking and Ordering Business Data", "sort_values with na_position|rank methods: average, min, max, dense|Ties and business meaning|Multi-index sorting|Ranking as feature engineering",
     "19,26", "01_pandas_tips_tricks/05_complete_EDA_google_playstore_data.ipynb", 2, "src"),
    (56, "Missing Values: Detection and Strategy", "Why missingness is information|isna, notna, isna().sum()|MCAR, MAR, MNAR intuition|Deletion strategies and their cost|Visualising missingness with missingno",
     "19,20,24", "07_machine_learning/02_missing_values.ipynb", 2, "src"),
    (57, "Imputation in Depth", "Mean, median, mode imputation|Forward and backward fill for time series|Group-wise imputation|KNN and iterative imputation|Using an ML model to impute (advanced)",
     "24,85", "07_machine_learning/02_missing_values.ipynb;07_machine_learning/24_impute_missing_values.ipynb;07_machine_learning/25_dl_missing_values.ipynb", 3, "src"),
    (58, "Duplicates and Inconsistent Values", "duplicated and drop_duplicates|Subset keys and keep strategies|Fuzzy near-duplicates|Fixing units, casing and whitespace|Category inconsistency mapping",
     "22,23", "07_machine_learning/03_inconsistencies_in_data.ipynb", 2, "src"),
    (59, "String Cleaning with the .str Accessor", "Vectorised string methods|split, extract with regex|replace, contains, startswith|Parsing messy currency and size columns|Performance tips for string ops",
     "21,22,26", "01_pandas_tips_tricks/04_kaggle_google_eda.ipynb", 3, "src"),
    (60, "Categorical Data and dtype Optimisation", "Object vs category dtype|Memory savings measurement|Ordered categories|groupby behaviour on categories|When category hurts",
     "21,60", "01_pandas_tips_tricks/05_complete_EDA_google_playstore_data.ipynb", 3, "ext"),
    (61, "Datetime Handling in Pandas", "to_datetime and errors='coerce'|dt accessor: year, month, weekday, hour|date_range, Period, resample|Business days and holidays|Datetime index benefits",
     "158,159,161", "08_deep_learning_with_tensorflow/10_time_series.ipynb;06_statistics/07_case_study.ipynb", 3, "src"),
    (62, "GroupBy Fundamentals", "Split-apply-combine|groupby on one and many keys|Iterating groups|Value counts vs groupby size|Group keys with NaN",
     "25,26", "01_pandas_tips_tricks/05_complete_EDA_google_playstore_data.ipynb", 3, "src"),
    (63, "Aggregation, Transform and Filter", "agg with dicts and named aggregation|transform for shape-preserving ops|filter for group-level selection|Normalising within groups|Percent of total calculations",
     "25,26", "01_pandas_tips_tricks/04a_EDA_google_playstore_data.ipynb", 3, "src"),
    (64, "apply, map, applymap and pipe", "When to use map vs apply vs applymap|Row-wise apply and its cost|Vectorised alternatives to apply|Method chaining with pipe|Writing readable transformation functions",
     "25,60", "01_pandas_tips_tricks/06_data_visualization.ipynb", 3, "src"),
    (65, "Merge and Join", "Relational thinking: keys|Inner, left, right, outer joins|Many-to-one and many-to-many|merge_asof for time-based joins|Validating join cardinality",
     "25,65", "07_machine_learning/05_data_integration.ipynb", 3, "src"),
    (66, "Concat and Combining DataFrames", "Vertical vs horizontal concatenation|Index handling and ignore_index|Mismatched columns|Building a master dataset from parts|Multi-source data integration patterns",
     "25,65", "07_machine_learning/05_data_integration.ipynb", 3, "src"),
    (67, "Pivot and pivot_table", "Long vs wide format|pivot vs pivot_table semantics|Aggregation functions in pivot_table|Multi-level columns downstream|Business reporting tables",
     "25,26", "01_pandas_tips_tricks/05_complete_EDA_google_playstore_data.ipynb", 3, "src"),
    (68, "Melt, Stack, Unstack and Crosstab", "melt for tidying data|stack and unstack mechanics|Crosstab for frequency analysis|Heatmap-ready formats|Tidy data principles",
     "25,26", "01_pandas_tips_tricks/07_plotting_seaborn.ipynb", 3, "ext"),
    (69, "Rolling Windows, Shifts and Lag Features", "rolling with window and min_periods|expanding and ewm|shift, diff, pct_change|Lag features for forecasting|Window leakage warning",
     "158,161,171", "08_deep_learning_with_tensorflow/10_time_series.ipynb", 3, "src"),
    (70, "Feature Engineering + Complete EDA Case Study", "Feature types: numeric, categorical, datetime, text|Creating ratios, aggregates, flags|Encoding domain knowledge|Full EDA narrative on the Google Play Store dataset|EDA report and next steps",
     "26,28,29", "01_pandas_tips_tricks/05_complete_EDA_google_playstore_data.ipynb;01_pandas_tips_tricks/data/googleplaystore.csv", 3, "src"),
]
