# Phase 9 - Days 151-164 : Excel + Power BI + Tableau
DAYS = [
    (151, "Excel for Data Analysts: Structure, Cleaning and Formulas", "Workbook anatomy: sheets, cells, ranges|Named ranges and structured tables|Absolute vs relative references|Sorting, filtering, remove duplicates, text-to-columns|Data validation and cleaning workflow",
     "151,220", "resources/datasets_for_practice/Sample_Superstore.xlsx", 2, "src"),
    (152, "Excel Formulas That Get You Hired", "IF and nested IF vs IFS|SUMIFS and COUNTIFS with criteria|XLOOKUP vs VLOOKUP|INDEX/MATCH combination|AVERAGEIFS and array-style thinking",
     "152,220", "resources/datasets_for_practice/Sample_Superstore.xlsx", 3, "src"),
    (153, "Excel Text, Date Functions and PivotTables", "TEXT, LEFT, RIGHT, MID, TRIM, CONCAT/TEXTJOIN|Date functions and date arithmetic|PivotTable fields, values, filters|Grouping dates in pivot tables|Pivot charts and slicers",
     "153,220", "resources/datasets_for_practice/Sample_Superstore.xlsx", 3, "src"),
    (154, "Excel Power Query and Dashboard Case Study", "Power Query as ETL: append, merge, unpivot|Refreshable data pipelines in Excel|Conditional formatting and KPI tiles|Dashboard layout grid|Full case study: sales dashboard from raw CSV",
     "154,220", "resources/datasets_for_practice/Sample_Superstore.xlsx;02_plotly_plots/data/GDP of Pakistan 1960-2021.xlsx", 3, "src"),
    (155, "Power BI Fundamentals and Interface", "BI vs BI-adjacent tools|Install, update and settings|Report view, data view, model view|Connect to Excel, CSV, SQL, web|Fields, visuals and the canvas",
     "240,241,242,243,244,245,246,247,248,249", "", 2, "src"),
    (156, "Power Query ETL in Power BI", "Get Data and query steps|Promote headers, change types, remove errors|Append and merge queries|Unpivot for tidy data|Parameters and query folding",
     "250,156", "resources/datasets_for_practice/Sample_Superstore.xlsx", 3, "src"),
    (157, "Data Modelling and Star Schema", "Fact vs dimension tables|Relationships, cardinality and direction|Star vs snowflake schema|Date table and marking as date table|Model best practices",
     "157,269", "", 3, "ext"),
    (158, "DAX I: Calculated Columns and Measures", "Row context vs filter context|Calculated column vs measure decision rule|Basic aggregations in DAX|Variables in DAX|Formatting and naming discipline",
     "158,265,269", "", 3, "src"),
    (159, "DAX II: CALCULATE, FILTER and Time Intelligence", "CALCULATE as the heart of DAX|FILTER and ALL/REMOVEFILTERS|Time intelligence: YTD, MTD, SAMEPERIODLASTYEAR|Ratios and percent-of-total|Debugging DAX with DAX Studio concepts",
     "159,266", "", 3, "ext"),
    (160, "Power BI Visuals, KPIs and Dashboard Design", "Chart selection inside Power BI|KPI cards, gauges, matrix visuals|Slicers, drill-through, bookmarks|Geo maps and filled maps|Dashboard project: sales analysis end to end",
     "251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,270,271,272,273,274", "", 3, "src"),
    (161, "Tableau Fundamentals", "Tableau Public install and interface|Dimensions vs measures|Discrete vs continuous (green vs blue)|Marks shelf and shelves logic|Loading and shaping data",
     "220,221,222,223,224,225", "", 2, "src"),
    (162, "Tableau Calculated Fields, Filters and Sorting", "Calculated field basics|Filters and context filters|Sorting, groups and sets|Parameters for interactivity|Data types and conversion",
     "226,227,228,229,230,231", "", 3, "src"),
    (163, "Tableau Charts, Dashboards and Stories", "Bar, line, scatter, area, map, treemap|Dual axis and combined charts|Dashboard layout and device preview|Story points for narrative flow|Publishing to Tableau Public",
     "232,233,234,235,236,237,238,239", "", 3, "src"),
    (164, "BI Capstone: End-to-End Dashboard and Business Storytelling", "Choose a business question and dataset|Model the data|Build the dashboard in Power BI or Tableau|Write the executive summary|Present and defend the dashboard",
     "164,270", "resources/datasets_for_practice/Sample_Superstore.xlsx;00_projects/03_bank_churn_kaggle_competition/figures", 3, "src"),
]
