# Phase 3 - Days 33-48 : NumPy + Scientific Computing
DAYS = [
    (33, "Why NumPy and the ndarray", "The speed problem with Python lists|ndarray: contiguous typed memory|Creating arrays: array, zeros, ones, arange, linspace|np.random basics|Why pandas is built on NumPy",
     "37,38", "04_numpy/01_numpy_intro.ipynb", 2, "src"),
    (34, "Dimensions, Shape and Axes", "0D to 3D+ arrays|shape, ndim, size, nbytes|Axis numbering and intuition|Reshaping mental model|Reading array shapes out loud",
     "37,38,39", "04_numpy/02_numpy.ipynb", 2, "src"),
    (35, "Data Types, Memory and Precision", "dtype system: int8-64, float16-64, bool, unicode|Memory footprint calculation|Casting and astype|Overflow and float precision traps|Choosing lean dtypes",
     "38,39", "04_numpy/03_numpy.ipynb", 3, "src"),
    (36, "Indexing, Slicing and Views vs Copies", "Basic indexing and slices|Negative and step slicing|Views share memory, copies do not|Fancy indexing with index arrays|Assigning through slices",
     "37,38", "04_numpy/02_numpy.ipynb", 2, "src"),
    (37, "Boolean Masking and Conditional Selection", "Comparison operators return boolean arrays|Mask-based filtering|np.where and np.select|Combining masks with & | ~|np.clip, np.isnan, np.isinf",
     "38,39,27", "04_numpy/03_numpy.ipynb;07_machine_learning/04_outliers.ipynb", 2, "src"),
    (38, "Reshape, Flatten, Transpose and Concatenate", "reshape and -1 inference|flatten vs ravel (copy vs view)|transpose and .T|stack, hstack, vstack, concatenate|Reshaping images to vectors",
     "38,39", "04_numpy/02_numpy.ipynb;09_computer_vision/01_image.ipynb", 2, "src"),
    (39, "Vectorisation: Thinking Without Loops", "What vectorisation really means at CPU level|Replacing loops with array expressions|Element-wise vs reduction operations|ufuncs and where they live|Benchmarking a loop versus a vectorised version",
     "39,30", "04_numpy/03_numpy.ipynb", 3, "ext"),
    (40, "Broadcasting Rules", "Broadcasting in three rules|Scalar and row/column broadcasting|Shape mismatch errors and how to read them|newaxis and expand_dims|Practical uses: normalisation, distance matrices",
     "39,47,48", "04_numpy/03_numpy.ipynb", 3, "src"),
    (41, "Aggregations and Axis Semantics", "sum, mean, std, min, max, argmin/argmax|axis=0 vs axis=1 demystified|keepdims and NaN-aware functions|percentile and quantile|Aggregating images and features",
     "38,39", "04_numpy/03_numpy.ipynb;06_statistics/01_central Tendency.ipynb", 2, "src"),
    (42, "Linear Algebra I: Vectors, Matrices and Products", "Vector and matrix representation|Element-wise vs matrix product|np.dot vs @ operator|Transpose rules for products|Matrix as a data table and as a transformation",
     "47,48,49,58", "05_mathematics/01_linear_algebra.ipynb", 3, "src"),
    (43, "Linear Algebra II: Inverse, Solve and Determinant", "Identity and inverse|np.linalg.inv and np.linalg.solve|Singular matrices and conditioning|Normal equation for linear regression|Determinant as volume scaling",
     "49,50,51", "05_mathematics/01_linear_algebra.ipynb", 3, "src"),
    (44, "Random Numbers and Simulation", "Why pseudo-randomness is reproducible|np.random.default_rng and Generator|Distributions: uniform, normal, binomial, poisson|Simulating dice, queues, portfolio returns|Monte Carlo estimation of pi",
     "44,45", "04_numpy/03_numpy.ipynb;06_statistics/02_distribution.ipynb", 3, "ext"),
    (45, "Numerical Stability and Precision", "Floating point is not real arithmetic|Catastrophic cancellation|Log-sum-exp trick|Normalising before distance computation|eps, NaN, inf handling in pipelines",
     "39,50", "04_numpy/03_numpy.ipynb", 3, "ext"),
    (46, "Performance: Strides, Memory Layout and Speed Tricks", "C vs Fortran order and strides|Cache-friendly iteration|In-place operations|Avoiding unnecessary copies|When NumPy still is not enough: numba, Numba-free options, Cython preview",
     "39,30", "04_numpy/03_numpy.ipynb", 3, "ext"),
    (47, "Scientific Computing Workflow + NumPy Project", "Simulation project: physics-style data generation|Building a mini statistics engine with NumPy|Reproducible random seeds|Code organisation for numerical work|Project write-up",
     "44,58", "04_numpy/01_numpy_intro.ipynb;04_numpy/02_numpy.ipynb", 3, "src"),
    (48, "NumPy Assessment and Consolidation", "40-question assessment|Five coding katas: masking, broadcasting, aggregation, linalg, simulation|Common errors recap|Debugging slow or wrong array code|Bridge to pandas",
     "37,38,39", "04_numpy/03_numpy.ipynb", 3, "src"),
]
