# Phase 2 - Days 16-32 : Python for Data Work
DAYS = [
    (16, "Object-Oriented Programming I: Classes and Objects", "Why OOP matters for data code|class, __init__, self|Instance vs class attributes|Methods and properties|Designing a small data class",
     "14,15,16", "07_machine_learning/09_basic_model_coding.ipynb", 2, "src"),
    (17, "OOP II: Inheritance, Polymorphism and Dataclasses", "Inheritance and super()|Method overriding and polymorphism|Dunder methods: __repr__, __len__, __eq__|Composition over inheritance|@dataclass and @property",
     "15,16", "07_machine_learning/20_pipeline.ipynb", 2, "src"),
    (18, "Iterators and the Iteration Protocol", "Iterable vs iterator|__iter__ and __next__|StopIteration and loops|Memory behaviour while iterating|Building a custom iterator",
     "16", "01_pandas_tips_tricks/01_pandas.ipynb", 2, "src"),
    (19, "Generators and Lazy Evaluation", "yield and generator functions|Generator expressions|Streaming big files without loading RAM|itertools toolbox|When laziness hurts",
     "16", "01_pandas_tips_tricks/data/googleplaystore.csv", 2, "src"),
    (20, "Decorators", "Functions as first-class objects|Closures and nonlocal|Writing your own decorator|functools.wraps|Practical decorators: timing, retry, caching (@lru_cache)",
     "16", "07_machine_learning/09_basic_model_coding.ipynb", 3, "src"),
    (21, "Context Managers", "with statement and resource safety|__enter__ / __exit__|contextlib.contextmanager|Managing files, DB connections and timers|Cleaning up on error paths",
     "16,176", "07_machine_learning/24_impute_missing_values.ipynb", 3, "src"),
    (22, "Type Hints and Modern Typing", "Why annotate code|Built-in generics: list[int], dict[str, float]|Optional, Union, Literal|TypedDict and dataclasses|Checking with mypy and enabling IDE help",
     "16", "07_machine_learning/20_pipeline.ipynb", 3, "ext"),
    (23, "Testing Your Data Code with pytest", "Why tests save data pipelines|assert-based sanity checks|Writing your first pytest test|Fixtures and parametrisation|Testing DataFrames and ETL outputs",
     "16,176", "07_machine_learning/09_basic_model_coding.ipynb", 3, "ext"),
    (24, "Logging Instead of Printing", "Why print() fails in production|logging levels and handlers|Formatting log records|Logging inside a data pipeline|Log rotation and structured logs",
     "16,176", "15_flask_web_apps/00_Complete_tutorials/01_basic_app/app.py", 3, "ext"),
    (25, "Debugging Like a Professional", "Reading a traceback bottom-up|print-debugging discipline|breakpoint() and pdb commands|Debugging inside VS Code and Jupyter|Rubber-duck method and bisecting bugs",
     "9,16,88", "07_machine_learning/01_installation.ipynb", 2, "src"),
    (26, "Regular Expressions for Data Cleaning", "Regex mental model: pattern -> match|Character classes and quantifiers|Groups, alternation and anchors|re.search, findall, sub, compile|Extracting and cleaning messy text fields",
     "16,168", "01_pandas_tips_tricks/05_complete_EDA_google_playstore_data.ipynb", 3, "ext"),
    (27, "HTTP, APIs and requests", "Client-server model|HTTP verbs, status codes, headers|GET with query parameters|Sending POST with JSON bodies|Timeouts, retries and rate limits",
     "188,14_langchain", "14_langchain/00_APIs.ipynb", 2, "src"),
    (28, "Web Data: JSON, HTML and Scraping with Pandas", "JSON structures and parsing|Nested JSON to DataFrame|HTML tables with pandas.read_html|Intro to BeautifulSoup|Scraping ethics and robots.txt",
     "168,169,170", "08_deep_learning_with_tensorflow/17_web_scrapping.ipynb;08_deep_learning_with_tensorflow/16_webscrapping_stock_market_data.ipynb", 2, "src"),
    (29, "datetime, timedelta and Time Zones", "datetime, date, time objects|Parsing strings into dates|Arithmetic with timedelta|Naive vs aware datetimes and tzinfo|UTC discipline in pipelines",
     "158,159,160", "08_deep_learning_with_tensorflow/10_time_series.ipynb", 2, "src"),
    (30, "Performance, Profiling and Refactoring", "Complexity intuition for data code|timeit and %timeit|Profiling with cProfile|Vectorise instead of loop|Refactoring for readability: naming, small functions, DRY",
     "16,30", "04_numpy/03_numpy.ipynb", 3, "ext"),
    (31, "Git, GitHub, Project Structure, CLI and Automation", "Git mental model and the three trees|commit, branch, merge, merge conflicts|Pushing to GitHub and pull requests|Standard project layout|argparse CLI and scheduling automation",
     "176,31", "README.md;.gitignore;.vscode/settings.json", 2, "src"),
    (32, "Python Data Pipeline Project and Mastery Assessment", "Pipeline design: extract -> transform -> load|Config files and logging in a real project|Code review checklist|Writing a README that recruiters read|Mastery assessment: 30 questions + 4 coding tasks",
     "31,101,102", "resources/datasets_for_practice/tips.csv;resources/datasets_for_practice/diamonds.csv", 3, "src"),
]
