# Phase 12 - Days 213-232 : Deep Learning + Computer Vision
DAYS = [
    (213, "Neural Networks from Zero: The Perceptron", "Biological to artificial neuron analogy|Weighted sum and threshold|Perceptron learning rule|XOR problem and the limits of a single neuron|From perceptron to multilayer networks",
     "125,126", "08_deep_learning_with_tensorflow/01_simple_nn.ipynb", 3, "src"),
    (214, "Neurons, Weights, Bias and Activation Functions", "Linear layer mathematics|Bias as a shift|Step, sigmoid, tanh, ReLU, Leaky ReLU, softmax|Why non-linearity is essential|Choosing activation by layer position",
     "130,131,132,134", "08_deep_learning_with_tensorflow/02_mlp.ipynb", 3, "src"),
    (215, "Loss Functions", "MSE and MAE for regression|Binary cross-entropy derivation|Categorical cross-entropy and softmax|Hinge and Huber losses|Matching loss to task and output layer",
     "127,215", "08_deep_learning_with_tensorflow/01_simple_nn.ipynb", 3, "src"),
    (216, "Gradient Descent and Backpropagation", "Computational graph of a network|Forward pass|Backward pass by hand for a 2-layer net|Vanishing and exploding gradients|Optimisers: SGD, momentum, RMSProp, Adam",
     "125,126,127", "08_deep_learning_with_tensorflow/01_simple_nn.ipynb", 3, "src"),
    (217, "Network Architecture: Depth, Width and Capacity", "Hidden layers and representation power|How many neurons per layer|Parameter counting|Universal approximation intuition|Capacity vs data size",
     "128,217", "08_deep_learning_with_tensorflow/02_mlp.ipynb", 3, "src"),
    (218, "Overfitting, Regularisation, Dropout and Batch Norm", "Underfitting vs overfitting learning curves|L1/L2 weight decay|Dropout mechanics and inference behaviour|Batch normalisation and internal covariate shift|Early stopping and data augmentation",
     "179,218", "08_deep_learning_with_tensorflow/20_overfitting_underfitting.ipynb;08_deep_learning_with_tensorflow/21_overfit_and_underfit.ipynb", 3, "src"),
    (219, "PyTorch I: Tensors", "Tensor creation and dtypes|Devices: CPU vs CUDA|Broadcasting and operations|Reshaping and views|NumPy interoperability",
     "219", "16_pytorch/01_basics.ipynb", 3, "mix"),
    (220, "PyTorch II: Autograd", "requires_grad and computational graph|backward() and gradient accumulation|Detaching and no_grad|Custom autograd functions|Gradient checking",
     "220", "16_pytorch/01_basics.ipynb", 3, "mix"),
    (221, "PyTorch III: nn.Module and the Training Loop", "Defining models with nn.Module|Layers: Linear, ReLU, Sequential|Loss functions and optimisers|Canonical training loop: zero_grad, forward, loss, backward, step|train() vs eval() modes",
     "221", "16_pytorch/01_basics.ipynb", 3, "mix"),
    (222, "PyTorch IV: Datasets, DataLoader, GPU and Checkpoints", "Custom Dataset class|DataLoader batching and shuffling|Moving data to GPU|Saving and loading checkpoints|Transferring between devices",
     "222", "16_pytorch/01_basics.ipynb", 3, "mix"),
    (223, "Training Best Practices, Schedules and Monitoring", "Learning rate finder and schedulers|Weight initialisation strategies|Tracking metrics with TensorBoard|Debugging training that will not converge|Experiment discipline",
     "183,223", "12_tensorboard/01_basics_of_tensorboard/tensorboard-for-tensorflow.ipynb;12_tensorboard/03_scalars_metrics/scalars_and_keras.ipynb", 3, "src"),
    (224, "Convolution: Filters, Stride, Padding and Feature Maps", "Why convolution for images|Kernel as learned pattern detector|Stride, padding, dilation|Output size formula|Feature maps and receptive fields",
     "143,145", "08_deep_learning_with_tensorflow/03_CNN.ipynb", 3, "src"),
    (225, "Pooling, CNN Architectures and Design", "Max and average pooling|Translation invariance|LeNet to ResNet evolution|Skip connections and depth|Parameter and FLOPs counting",
     "143,225", "08_deep_learning_with_tensorflow/5a_CNN.ipynb", 3, "src"),
    (226, "Image Classification with PyTorch CNNs", "Loading image datasets|Building a CNN in PyTorch|Training and validating|Confusion matrix and per-class metrics|Saving and loading the best model",
     "146,226", "08_deep_learning_with_tensorflow/04_CNN_fashion_mnist.ipynb;09_computer_vision/01_image.ipynb", 3, "src"),
    (227, "Data Augmentation", "Augmentation as regularisation|Geometric and photometric transforms|Augmentation pipelines in torchvision|Mixup and CutMix previews|Common augmentation mistakes",
     "227", "10_transfer_learning/04_crop_net/cropnet_cassava.ipynb", 3, "ext"),
    (228, "Transfer Learning and Fine-Tuning", "Feature extraction vs fine-tuning|Frozen layers and new heads|Learning rate strategies for fine-tuning|When transfer learning fails|Implementation with torchvision and Hugging Face",
     "181,228", "10_transfer_learning/02_transfer_learning_and_fine_tuning/transfer_learning.ipynb;10_transfer_learning/03_tensorflow_hub/transfer_learning_with_hub.ipynb", 3, "src"),
    (229, "CNN Evaluation and Error Analysis", "Beyond accuracy: per-class precision/recall|Confusion matrix analysis|Grad-CAM visualisation|Finding and fixing label errors|Error taxonomy before retraining",
     "229,147", "09_computer_vision/01_image.ipynb", 3, "ext"),
    (230, "Recurrent Neural Networks", "Sequential data and memory|RNN cell equations|BPTT and vanishing gradients|Truncated backpropagation through time|Implementing an RNN for sequences",
     "149,150,151,152", "08_deep_learning_with_tensorflow/06_RNN_LSTM_GRU.ipynb", 3, "src"),
    (231, "LSTM and GRU", "Gates: forget, input, output|Cell state as long-term memory|GRU simplification|When to choose LSTM vs GRU|Comparison experiments on the same data",
     "155,156,157", "08_deep_learning_with_tensorflow/06_RNN_LSTM_GRU.ipynb", 3, "src"),
    (232, "Sequence Modelling in PyTorch + Deep Learning Capstone", "Embedding layers|Packing and padding sequences|Text and time-series RNNs in PyTorch|Capstone: image + sequence project review|Model card and documentation",
     "232,147", "08_deep_learning_with_tensorflow/09_RNN_text_classification.ipynb;16_pytorch/01_basics.ipynb", 3, "src"),
]
