# Phase 13 - Days 233-246 : NLP + Transformers + Hugging Face
DAYS = [
    (233, "The NLP Pipeline and Text Preprocessing", "NLP task taxonomy|Corpus, documents, tokens|Cleaning: HTML, URLs, unicode, emoji|Lowercasing, stopwords, stemming, lemmatisation|Trade-offs: cleaning can destroy signal",
     "153,233", "08_deep_learning_with_tensorflow/09_RNN_text_classification.ipynb", 2, "src"),
    (234, "Tokenization: From Words to Subwords", "Word, character and subword tokenization|Vocabulary size trade-offs|Byte-pair encoding (BPE)|WordPiece and SentencePiece|OOV handling and tokenizer training",
     "153,234", "10_transfer_learning/05_hugging_face/01_basics.ipynb", 3, "src"),
    (235, "Bag of Words and TF-IDF", "Document-term matrix|CountVectorizer in sklearn|TF-IDF weighting and intuition|N-grams and feature explosion|Baseline text classification pipeline",
     "154,235", "07_machine_learning/22_naive_bayes.ipynb", 3, "src"),
    (236, "Word Embeddings", "One-hot limits|Distributional hypothesis|Word2Vec CBOW and skip-gram|GloVe and FastText|Embedding arithmetic and analogies",
     "236", "10_transfer_learning/05_hugging_face/01_basics.ipynb", 3, "src"),
    (237, "Sequence Models for Text", "RNN/LSTM text classification end to end|Padding, masking and variable length|Bidirectional layers|Sequence labelling: POS and NER|Limits of recurrence",
     "154,237", "08_deep_learning_with_tensorflow/09_RNN_text_classification.ipynb", 3, "src"),
    (238, "The Attention Mechanism", "Bottleneck of fixed-size context vectors|Query, key, value formulation|Attention weights as soft alignment|Bahdanau vs Luong attention|Visualising attention weights",
     "238", "10_transfer_learning/05_huggingface_01/01_basics.ipynb", 3, "ext"),
    (239, "Self-Attention and Multi-Head Attention", "Scaled dot-product attention maths|Why divide by sqrt(d_k)|Multi-head attention|Computational complexity O(n^2)|Implementing attention in PyTorch",
     "239", "16_pytorch/01_basics.ipynb", 3, "ext"),
    (240, "The Transformer Architecture", "Encoder-decoder structure|Positional encoding: sinusoidal and learned|Residual connections and layer norm|Feed-forward blocks|Full architecture diagram walkthrough",
     "240", "10_transfer_learning/05_hugging_face/01_basics.ipynb", 3, "ext"),
    (241, "BERT and Encoder-Only Models", "Masked language modelling|Next sentence prediction and its removal|BERT variants: RoBERTa, DistilBERT, DeBERTa|Best tasks for encoders|CLS pooling and sentence embeddings",
     "241", "10_transfer_learning/05_huggingface_01/01_basics.ipynb", 3, "src"),
    (242, "Generative Transformers and Decoding Strategies", "Decoder-only architecture and causal masking|GPT family scaling laws intuition|Greedy, beam, top-k, top-p sampling|Temperature and repetition penalties|T5 and encoder-decoder generation",
     "242", "11_generative_AI/02_stable_diffusion/00_Diffusion_models.ipynb", 3, "ext"),
    (243, "Hugging Face: The Transformers Library", "Hub, models and model cards|pipeline() for quick inference|AutoTokenizer and AutoModel classes|Tokenization->model->post-processing flow|Choosing the right checkpoint",
     "187,243", "10_transfer_learning/05_hugging_face/01_basics.ipynb;10_transfer_learning/05_huggingface_01/01_basics.ipynb", 3, "src"),
    (244, "Hugging Face: Tokenizers and Datasets Libraries", "Fast tokenizers and offset mapping|Padding, truncation, attention masks|Loading and streaming datasets|map(), filter(), set_format|Pushing to and pulling from the Hub",
     "244", "10_transfer_learning/05_hugging_face/01_basics.ipynb", 3, "ext"),
    (245, "Fine-Tuning a Transformer Classifier", "Task setup and label mapping|Trainer API vs custom PyTorch loop|Learning rate, warmup, weight decay|Evaluation during training|Saving, versioning and serving the model",
     "245", "10_transfer_learning/02_transfer_learning_and_fine_tuning/transfer_learning.ipynb", 3, "src"),
    (246, "NLP Evaluation, Error Analysis and Capstone", "Metrics per task: F1, EM, BLEU, ROUGE, perplexity|Confusion analysis for text|Slice analysis by length, domain, language|Bias and fairness checks|Capstone: end-to-end NLP project",
     "246,154", "08_deep_learning_with_tensorflow/09_RNN_text_classification.ipynb", 3, "mix"),
]
