# Phase 6 - Days 89-112 : Mathematics for Data Science
DAYS = [
    (89, "Why Mathematics and Number Sense", "Math as the language of models|Arithmetic proficiency checks|Order of operations and percentages|Estimation and sanity checking|Math anxiety management",
     "40,41", "05_mathematics/01_linear_algebra.ipynb", 1, "src"),
    (90, "Fractions, Ratios, Proportions and Percentages", "Fractions and decimal equivalence|Ratios and rates|Percentage change, points and growth|Proportions in data (share of total)|Applied: conversion rates and metrics",
     "41,42", "05_mathematics/01_linear_algebra.ipynb", 1, "src"),
    (91, "Number Theory Essentials", "Natural, integer, rational, real, complex|Primes and factorisation|GCD and LCM|Modular arithmetic and hashing|Number theory in cryptography and hashing",
     "41,42,43", "05_mathematics/01_linear_algebra.ipynb", 2, "src"),
    (92, "Pre-Algebra and Algebraic Manipulation", "Variables and expressions|Expanding and factorising|Solving linear equations|Transposing formulas (e.g. z-score, RMSE)|Word problems to equations",
     "43,44,45", "05_mathematics/01_linear_algebra.ipynb", 2, "src"),
    (93, "Equations, Inequalities and Linear Systems", "Linear equations in two variables|Inequalities and interval notation|Systems of equations: substitution and elimination|Matrix view of linear systems|Feasible regions and constraints",
     "45,46,93", "05_mathematics/01_linear_algebra.ipynb", 2, "src"),
    (94, "Functions and Graphs", "Function as a mapping|Domain, range, inverse|Linear, quadratic, exponential, sigmoid, ReLU|Graph reading: intercepts, slopes, asymptotes|Why ML models are functions",
     "46,47", "05_mathematics/01_linear_algebra.ipynb", 2, "src"),
    (95, "Exponents and Logarithms", "Exponent laws|Log as inverse of exponent|Log base e, 2 and 10|Log-scale data and why ML loves logs|Cross-entropy and log-likelihood preview",
     "46,47", "05_mathematics/01_linear_algebra.ipynb", 2, "src"),
    (96, "Sequences, Series and Summation Notation", "Arithmetic and geometric sequences|Sigma notation reading|Sum formulas and intuitions|Infinite series and convergence|Sums appearing in ML losses",
     "47,96", "05_mathematics/01_linear_algebra.ipynb", 3, "src"),
    (97, "Coordinate Geometry and Distances", "Cartesian plane and points|Slope, intercept and line equation|Euclidean and Manhattan distance|Distance in n dimensions|Distance as the core of KNN and clustering",
     "47,48", "05_mathematics/01_linear_algebra.ipynb", 2, "src"),
    (98, "Vectors: Operations and Norms", "Vector as ordered list and as arrow|Addition, subtraction, scalar multiplication|L1, L2, L-infinity norms|Unit vectors and normalisation|Feature vectors in ML",
     "47,48,49", "05_mathematics/01_linear_algebra.ipynb", 3, "src"),
    (99, "Dot Product, Angles and Projections", "Dot product algebra and geometry|Cosine similarity|Orthogonality and correlation link|Projection formula|Applications: cosine similarity in search and NLP",
     "48,49,50", "05_mathematics/01_linear_algebra.ipynb", 3, "src"),
    (100, "Matrices: Representation and Operations", "Matrix notation and shapes|Addition, scalar multiplication|Transpose and symmetric matrices|Identity, diagonal and triangular matrices|Data as matrix: rows = samples, columns = features",
     "49,50,100", "05_mathematics/01_linear_algebra.ipynb", 3, "src"),
    (101, "Matrix Multiplication and Its Meaning", "Inner-dimension rule|Manual multiplication walkthrough|Matrix x vector as transformation|Computational cost and associativity|Where matmul appears: linear layers, attention",
     "50,51", "05_mathematics/01_linear_algebra.ipynb", 3, "src"),
    (102, "Linear Transformations and Geometry", "Transformation view: rotate, scale, shear, project|Basis vectors and how they move|Composition of transformations|Rank and null space intuition|Why neural networks are composed transformations",
     "51,52", "05_mathematics/01_linear_algebra.ipynb", 3, "src"),
    (103, "Determinants and Volume", "2x2 determinant formula and geometry|3x3 determinant and cofactor expansion|Determinant as area/volume scale factor|Sign of determinant and orientation|Determinant zero means information loss",
     "52,53", "05_mathematics/01_linear_algebra.ipynb", 3, "src"),
    (104, "Matrix Inverse and Solving Linear Systems", "Identity check for inverses|2x2 inverse derivation|Gaussian elimination preview|np.linalg.solve vs inv|Singular and ill-conditioned matrices",
     "53,54", "05_mathematics/01_linear_algebra.ipynb", 3, "src"),
    (105, "Eigenvalues and Eigenvectors", "Definition: Av = lambda v|Finding eigenvalues via characteristic polynomial|Eigenvectors as invariant directions|Symmetric matrices and orthogonality|Computation with NumPy",
     "54,55,56", "05_mathematics/01_linear_algebra.ipynb", 3, "src"),
    (106, "Eigen-Decomposition and Applications", "Diagonalisation A = P D P^-1|Matrix powers and PageRank idea|Covariance eigen-structure -> PCA|Variance explained by eigen values|Spectral clustering preview",
     "55,56,57", "05_mathematics/01_linear_algebra.ipynb;07_machine_learning/unsupervised_machine_learning/20_PCA.ipynb", 3, "src"),
    (107, "Derivatives: Definition, Rules and Intuition", "Slope as instantaneous rate of change|Limit definition|Power, product, quotient and chain rules|Derivatives of exp, log, sigmoid|Second derivative and curvature",
     "57,107", "05_mathematics/01_linear_algebra.ipynb", 3, "ext"),
    (108, "Partial Derivatives and Gradients", "Functions of many variables|Partial derivative notation|Gradient as a vector of steepest ascent|Level curves and contour plots|Gradient of MSE and cross-entropy",
     "57,107", "05_mathematics/01_linear_algebra.ipynb", 3, "ext"),
    (109, "Chain Rule and Backpropagation Preview", "Composition of functions|Chain rule single and multi variable|Computational graph intuition|Forward and backward pass by hand|Why autograd exists",
     "107,125", "08_deep_learning_with_tensorflow/01_simple_nn.ipynb", 3, "ext"),
    (110, "Optimisation and Gradient Descent Mathematics", "Minima, maxima, saddle points|Convexity and local minima|Gradient descent update rule|Learning rate effects and convergence|Momentum, RMSProp, Adam as refinements",
     "106,107", "07_machine_learning/10_linear_regression.ipynb", 3, "src"),
    (111, "Probability Foundations", "Sample space, events, axioms|Combining events: union, intersection|Conditional probability|Independence and mutual exclusivity|Counting rules and permutations",
     "59,60,61", "06_statistics/02_distribution.ipynb", 3, "src"),
    (112, "Bayes, Random Variables and Distributions + Math for ML Capstone", "Bayes theorem derivation and intuition|Random variables discrete and continuous|PMF, PDF, CDF|Expectation and variance|Capstone: derive linear regression cost and solve it",
     "61,63,106", "06_statistics/02_distribution.ipynb;05_mathematics/01_linear_algebra.ipynb", 3, "src"),
]
