# Phase 14 - Days 247-258 : Generative AI + LLMs + RAG
DAYS = [
    (247, "Generative AI and LLM Fundamentals", "GenAI: what generative AI means|LLM training stages: pretraining, SFT, RLHF/DPO|Model families and sizes|Capabilities and hard limits|Choosing an LLM for a task",
     "180,182,186,247", "11_generative_AI", 3, "src"),
    (248, "Tokens, Context Windows and Sampling Parameters", "Tokenization effects on cost and behaviour|Context window budgets|Temperature, top-p, top-k, seed|Max tokens, stop sequences, penalties|Cost and latency engineering",
     "248,186", "14_langchain/00_APIs.ipynb", 3, "src"),
    (249, "Prompt Engineering", "Prompt anatomy: role, task, context, format, constraints|System vs user vs assistant messages|Zero-shot, few-shot, chain-of-thought|Self-consistency and decomposition|Prompt evaluation and iteration",
     "186,249", "14_langchain/01_langchain.ipynb", 3, "src"),
    (250, "Structured Outputs and Function Calling", "Why free text breaks pipelines|JSON schema and Pydantic validation|Function/tool calling flow|Retry and repair strategies|Parsing LLM output safely",
     "250,188", "14_langchain/02_LangChain.ipynb", 3, "ext"),
    (251, "Embeddings and Semantic Search", "Embedding space intuition|Sentence-transformer models|Cosine similarity retrieval|Embedding models vs LLM dimensions|Building a semantic search index",
     "188,251", "13_streamlit/07_ask_the_documents/main.py", 3, "src"),
    (252, "Vector Databases and Indexing", "Why vector databases exist|Flat, IVF, HNSW, PQ indexes|FAISS, Chroma, Pinecone, pgvector|Metadata filtering and hybrid search|Insert, update, delete and reindexing",
     "252,188", "13_streamlit/16_RAG_based_chatpdf/app.py", 3, "ext"),
    (253, "Chunking and Document Processing", "PDF and DOCX extraction|Fixed, recursive, semantic chunking|Chunk size and overlap trade-offs|Tables, images and layout handling|Chunk metadata design",
     "253,168", "13_streamlit/15_chat_with_multiple_pdfs/app.py;13_streamlit/07_ask_the_documents", 3, "src"),
    (254, "RAG Architecture End to End", "Why RAG instead of fine-tuning|Indexing pipeline vs query pipeline|Retriever + reranker + generator|Prompt assembly with citations|Building a working RAG app",
     "188,254", "13_streamlit/07_ask_the_documents/main.py;13_streamlit/09_ask_any_document/openai_doc_api_app.py", 3, "src"),
    (255, "RAG Evaluation, Hallucination and Grounding", "Faithfulness, answer relevance, context precision/recall|RAGAS-style evaluation|Golden datasets and regression testing|Hallucination taxonomy and mitigation|Grounding with citations and refusal behaviour",
     "255", "13_streamlit/16_RAG_based_chatpdf/app.py", 3, "ext"),
    (256, "LangChain: Chains, LCEL and Memory", "LangChain building blocks|Prompt templates and output parsers|LCEL composition with pipes|Conversation memory and state|Debugging and tracing chains",
     "188,256", "14_langchain/03_LangChain Cookbook Part 1 - Fundamentals.ipynb", 3, "src"),
    (257, "LangChain: Tools, Agents and Application Architecture", "Tools as callable functions|ReAct agent loop|Agent executors and error handling|When agents beat pipelines|Application architecture for LLM apps",
     "257,188", "14_langchain/04_LangChain Cookbook Part 2 - Use Cases.ipynb;13_streamlit/05_langchain_14_lines/main.py", 3, "src"),
    (258, "Safety, Reliability and the Document Intelligence Project Brief", "Prompt injection and jailbreaks|PII handling and data governance|Guardrails, moderation and allow-lists|Reliability patterns: caching, timeouts, fallbacks|Project brief: Document Intelligence RAG system",
     "258", "13_streamlit/06_Streamlit_secrets_APIs/main.py", 3, "mix"),
]
