# Phase 8 - Days 135-150 : SQL + Databases  (ACADEMY EXTENSION - not covered in the original course recordings)
DAYS = [
    (135, "Databases and the Relational Model", "Why SQL is non-negotiable for data roles|Tables, rows, columns, schema|Primary keys, foreign keys, constraints|Relationships and ER thinking|Setting up SQLite/Postgres and the practice database",
     "s-01", "resources/datasets_for_practice/database.sqlite.zip", 2, "ext"),
    (136, "SELECT, WHERE and ORDER BY", "SELECT clause and projections|Aliases|WHERE with comparison and logical operators|BETWEEN, IN, LIKE patterns|ORDER BY, LIMIT and deterministic sorting",
     "s-02", "resources/datasets_for_practice/database.sqlite.zip;resources/datasets_for_practice/Sample_Superstore.xlsx", 2, "ext"),
    (137, "Expressions, CASE and NULL Handling", "Arithmetic and string expressions|CASE WHEN for conditional logic|Binning with CASE|NULL semantics and three-valued logic|COALESCE and NULLIF",
     "s-03", "resources/datasets_for_practice/database.sqlite.zip", 2, "ext"),
    (138, "Aggregate Functions, GROUP BY and HAVING", "COUNT, COUNT(*), COUNT(DISTINCT)|SUM, AVG, MIN, MAX|GROUP BY rules|HAVING vs WHERE|Grouped business metrics",
     "s-04", "resources/datasets_for_practice/database.sqlite.zip", 3, "ext"),
    (139, "Joins I: Inner, Left, Right", "Join as key matching|INNER JOIN mechanics|LEFT JOIN and NULL rows|RIGHT JOIN and why it is rare|Join cardinality and row explosion",
     "s-05", "resources/datasets_for_practice/database.sqlite.zip", 3, "ext"),
    (140, "Joins II: Full, Cross, Self and Anti-Joins", "FULL OUTER JOIN|CROSS JOIN for combinations|SELF JOIN for hierarchies and comparisons|Anti-join pattern with NOT EXISTS / LEFT JOIN IS NULL|Semi-joins",
     "s-06", "resources/datasets_for_practice/database.sqlite.zip", 3, "ext"),
    (141, "Subqueries: Scalar, Derived and Correlated", "Scalar subqueries in SELECT and WHERE|IN and EXISTS|Derived tables in FROM|Correlated subqueries and performance|Rewriting subqueries as joins",
     "s-07", "resources/datasets_for_practice/database.sqlite.zip", 3, "ext"),
    (142, "CTEs and Modular SQL", "WITH clause syntax|Chaining multiple CTEs|Readable analytical pipelines|Recursive CTEs for hierarchies and series|CTE vs temp table vs view",
     "s-08", "resources/datasets_for_practice/database.sqlite.zip", 3, "ext"),
    (143, "Window Functions I: Ranking", "OVER() and PARTITION BY|ROW_NUMBER, RANK, DENSE_RANK, NTILE|Top-N per group pattern|Ordering inside partitions|Frames vs partitions",
     "s-09", "resources/datasets_for_practice/database.sqlite.zip", 3, "ext"),
    (144, "Window Functions II: Aggregates, Lags and Leads", "Running totals and moving averages|LAG and LEAD for trend analysis|FIRST_VALUE, LAST_VALUE, NTH_VALUE|Period-over-period change|Frame clauses ROWS vs RANGE",
     "s-10", "resources/datasets_for_practice/database.sqlite.zip", 3, "ext"),
    (145, "Date and String Functions for Analytics", "Date parsing, truncation, difference|EXTRACT and date arithmetic|String concatenation, SUBSTRING, TRIM, REPLACE|Pattern matching and regex in SQL|Building a clean date dimension",
     "s-11", "resources/datasets_for_practice/database.sqlite.zip", 3, "ext"),
    (146, "Data Cleaning in SQL", "Detecting duplicates with window functions|Standardising categories with CASE and mapping|Trimming and casing text|Handling bad dates and sentinel values|Building a cleaning layer as views",
     "s-12", "resources/datasets_for_practice/database.sqlite.zip", 3, "ext"),
    (147, "Analytical SQL Patterns", "Cohort analysis with retention grids|Funnel analysis with CTEs|Customer segmentation queries|RFM analysis|Period comparison and growth rates",
     "s-13", "resources/datasets_for_practice/database.sqlite.zip", 3, "ext"),
    (148, "Indexes, Query Plans and Optimisation", "How indexes work (B-tree intuition)|Composite indexes and column order|SARGable predicates|Reading EXPLAIN / EXPLAIN ANALYZE|Partitioning and materialised views",
     "s-14", "resources/datasets_for_practice/database.sqlite.zip", 3, "ext"),
    (149, "Normalisation, Transactions and ACID", "1NF, 2NF, 3NF with examples|When to denormalise (warehouse star schema)|Transactions and BEGIN/COMMIT/ROLLBACK|ACID properties explained|Isolation levels and concurrency anomalies",
     "s-15", "resources/datasets_for_practice/database.sqlite.zip", 3, "ext"),
    (150, "SQL Interview Sprint and Case Study", "12 classic interview questions solved live|Query optimisation interview scenarios|Window function interview patterns|Case study: retail revenue analysis from raw tables|Take-home SQL test strategy",
     "s-16", "resources/datasets_for_practice/database.sqlite.zip;resources/datasets_for_practice/Sample_Superstore.xlsx", 3, "ext"),
]
