# Phase 1 - Days 1-15 : Data Science + Python Foundations
# Row format: (day, title, "topic|topic|...", "transcript_ids", "repo/paths", difficulty(1-3), tag)
DAYS = [
    (1, "What is Data Science?", "Definition of data science|The three pillars: statistics, computing, domain|Data science vs BI vs data analytics|The 275-day journey ahead|Tools of the trade",
     "10,1,3,4", "README.md", 1, "src"),
    (2, "Data Analyst vs Data Scientist vs ML Engineer vs AI Engineer", "Four roles compared|Skill matrix and overlap|What each role does daily|Salary arc and hiring expectations|Choosing your track",
     "10,3,4,148", "README.md", 1, "src"),
    (3, "The Data Science Workflow", "CRISP-DM and its six phases|Problem framing before code|Data acquisition to deployment|Where projects fail|Iteration and feedback loops",
     "10,11,12", "README.md;00_projects/03_bank_churn_kaggle_competition/bank_churn_codanics.ipynb", 1, "src"),
    (4, "Setting Up Your Python Environment", "Installing Python and Anaconda|Conda environments explained|VS Code setup and extensions|Virtual environments vs conda envs|Troubleshooting broken installs",
     "6,5,7,202", "installation_script.sh;.vscode/settings.json", 1, "src"),
    (5, "Jupyter, Colab, Packages and Reproducibility", "Notebook anatomy, cells and kernels|Jupyter vs Colab vs VS Code|Installing and managing packages|requirements.txt and environment.yml|Reproducibility rules",
     "5,6,7,100", "installation_script.sh", 1, "src"),
    (6, "Variables, Data Types and Operators", "Variables as names bound to objects|Core types: int, float, str, bool, NoneType|type(), isinstance(), casting|Arithmetic, comparison and logical operators|Operator precedence",
     "14,15", "01_pandas_tips_tricks/01_pandas.ipynb", 1, "src"),
    (7, "Strings in Depth", "String literals and escapes|Indexing and slicing strings|Immutability|Common methods: split, join, strip, replace, find|f-strings and formatting",
     "14,15", "01_pandas_tips_tricks/01_pandas.ipynb", 1, "src"),
    (8, "Lists and Tuples", "List creation and mutability|append, extend, insert, pop, remove|Nested lists|Tuples and immutability|When to use which",
     "14,15", "04_numpy/01_numpy_intro.ipynb", 1, "src"),
    (9, "Sets and Dictionaries", "Set uniqueness and hash semantics|Union, intersection, difference|Dictionary as key-value store|Nested dictionaries and records|Real-world use cases",
     "15,16", "01_pandas_tips_tricks/01_pandas.ipynb", 1, "src"),
    (10, "Indexing and Slicing Mastery", "Zero-based indexing|Negative indices|Slicing with start, stop, step|Slice assignment and copies|Common off-by-one errors",
     "15,16", "04_numpy/02_numpy.ipynb", 1, "src"),
    (11, "Conditions and Branching Logic", "Boolean expressions and truthiness|if / elif / else|Ternary expressions|Guard clauses and readable branching|Nested conditions anti-pattern",
     "15,16", "07_machine_learning/01_installation.ipynb", 1, "src"),
    (12, "Loops and Iteration Tools", "for loops over sequences|while loops and loop control|range, enumerate, zip|break, continue, else|Nested loops and complexity",
     "15,16", "01_pandas_tips_tricks/01_pandas.ipynb", 1, "src"),
    (13, "Functions, Arguments and Scope", "Defining and calling functions|Positional, keyword, default, *args, **kwargs|Return values vs printing|LEGB scope rules|Docstrings",
     "16", "03_Feature_scaling_and_encoding/01_feature_scaling.ipynb", 1, "src"),
    (14, "Lambda, map, filter, Modules and Packages", "Anonymous functions|map and filter mental model|List vs generator expression|import forms|__name__ == '__main__' and building your own module",
     "16,18", "01_pandas_tips_tricks/01_pandas.ipynb", 2, "src"),
    (15, "Exceptions, Debugging, Files, JSON and pathlib + Foundation Project", "try / except / else / finally|Reading and writing files safely|JSON serialisation|pathlib for portable paths|Day-15 Python foundation project",
     "16,27", "resources/datasets_for_practice/tips.csv;https://github.com/gauskhan707/six-months_python_for_data_science-mentorship-program", 2, "src"),
]
