# Phase 5 - Days 71-88 : Data Visualization + Storytelling
DAYS = [
    (71, "Visualization Principles and Chart Selection", "Purpose first: explore vs explain|Perceptual accuracy of encodings|Choosing chart type for the question|Colour, labels and clutter|Anti-patterns: pie charts, dual axes, 3D",
     "30,32,33", "01_pandas_tips_tricks/06_data_visualization.ipynb;01_pandas_tips_tricks/outputs/plots", 2, "src"),
    (72, "Matplotlib Anatomy: Figure and Axes", "Figure, Axes, Axis objects|pyplot vs object-oriented API|subplots and gridspec|Sizing, DPI and saving figures|Styling with rcParams",
     "30,32", "01_pandas_tips_tricks/06_data_visualization.ipynb", 2, "src"),
    (73, "Line, Bar and Scatter Plots", "plot(), bar(), scatter() mechanics|Line styles, markers, widths|Bar plot ordering and baselines|Scatter with size and colour|When each plot answers which question",
     "30,32,35", "01_pandas_tips_tricks/outputs/plots/line_chart.png;01_pandas_tips_tricks/outputs/plots/bar_chart.png", 2, "src"),
    (74, "Histograms and Distribution Analysis", "Binning and bin width choice|hist, kde, ecdf|Comparing distributions across groups|Log scales for skewed data|Distribution shapes as modelling evidence",
     "33,74", "06_statistics/02_distribution.ipynb", 2, "src"),
    (75, "Boxplots, Violin Plots and Outlier Communication", "Five-number summary visualised|IQR fences on the plot|Violin plots and density shapes|Showing outliers honestly|Boxen and strip plots",
     "27,33,75", "07_machine_learning/04_outliers.ipynb;01_pandas_tips_tricks/outputs/plots/boxplot.png", 2, "src"),
    (76, "Scatterplots, Relationships and Bubble Charts", "Correlation visually|Overplotting and transparency|Bubble size encoding|Trend lines and regression overlay|Plotly bubble charts",
     "35,76", "02_plotly_plots/02_plotly_15_plots.ipynb;02_plotly_plots/output/bubble_chart_plotly.png", 2, "src"),
    (77, "Categorical Charts: Bars, Counts and Heatmaps", "Countplots and barplots|Stacked vs grouped bars|Ordering by value, not alphabet|Heatmaps for category pairs|Point plots with confidence intervals",
     "33,34", "01_pandas_tips_tricks/07_plotting_seaborn.ipynb;00_projects/03_bank_churn_kaggle_competition/figures/categorical_columns_countplot.png", 2, "src"),
    (78, "Time Series Plots and Annotations", "Datetime axis handling|Trend, seasonality and holiday bands|Annotating events on a chart|Shading uncertainty bands|Plotly time series interactivity",
     "161,33,35", "02_plotly_plots/output/time_series_plotly.html;08_deep_learning_with_tensorflow/10_time_series.ipynb", 3, "src"),
    (79, "Storytelling with Data", "Audience and decision framing|Headline, subtitle, caption structure|Annotation as narrative|One chart, one message|Presentation of EDA findings",
     "31,101,102", "01_pandas_tips_tricks/outputs/plots", 3, "src"),
    (80, "Seaborn I: Relational Plots", "relplot and figure-level vs axes-level|Hue, size, style semantics|Faceting with col and row|PairGrid basics|Seaborn theme control",
     "34,80", "01_pandas_tips_tricks/07_plotting_seaborn.ipynb", 2, "src"),
    (81, "Seaborn II: Distribution and Regression Plots", "displot with multiple kinds|kdeplot bandwidth effects|histplot with hue and multiple|lmplot and regplot|residplot for residual checking",
     "34,81", "01_pandas_tips_tricks/07_plotting_seaborn.ipynb", 3, "src"),
    (82, "Seaborn III: Categorical Plots", "boxplot, violinplot, boxenplot|barplot vs countplot|pointplot and catplot|Estimators and error bars|Ordering and palette choices",
     "34,82", "01_pandas_tips_tricks/outputs/plots/sns_boxplot.png", 3, "src"),
    (83, "Correlation and Heatmaps", "Pearson vs Spearman vs Kendall|corr() and method selection|Masking the upper triangle|Annotated heatmaps at readable scale|Correlation is not causation (formally)",
     "72,78,83", "06_statistics/06_correlation.ipynb;00_projects/03_bank_churn_kaggle_competition/figures/correlation_heatmap.png", 3, "src"),
    (84, "Pairplots and Multivariate Exploration", "pairplot for quick multivariate scan|pairplot performance limits|jointplot with marginals|clustermap for hierarchical ordering|Multivariate outlier spotting",
     "34,84", "01_pandas_tips_tricks/07_plotting_seaborn.ipynb", 3, "src"),
    (85, "Plotly I: Interactive Charts", "Why interactivity changes analysis|graph_objects vs express|Hover, zoom, legend interactions|Themes and templates|Exporting HTML and PNG",
     "33,35,85", "02_plotly_plots/01_plotly.ipynb;02_plotly_plots/02_plotly_15_plots.ipynb", 3, "src"),
    (86, "Plotly II: Animated, Geo and Hierarchical Charts", "Animation frames over time|Choropleth and scatter geo maps|Sunburst and treemap hierarchies|3D scatter plots|Publishing interactive figures",
     "35,86", "02_plotly_plots/03_sunburst.ipynb;02_plotly_plots/04_animated_plots.ipynb;02_plotly_plots/05_geo_maps.ipynb", 3, "src"),
    (87, "Interactive Dashboards with Plotly and Streamlit", "Dashboard layout thinking|Filters and cross-filtering|KPI tiles and drill-down|Streamlit + Plotly integration|Performance of interactive apps",
     "189,190,196", "13_streamlit/03_ml_app/app.py;02_plotly_plots/output/world_map_plotly.html", 3, "mix"),
    (88, "Visualization Project and Critique", "Brief: executive dashboard for a retail dataset|Chart-by-chart justification|Before/after redesign exercise|Accessibility and colour-blind safety|Peer critique rubric",
     "31,32,101", "01_pandas_tips_tricks/05_complete_EDA_google_playstore_data.ipynb;00_projects/03_bank_churn_kaggle_competition/figures", 3, "src"),
]
